SRCS = ft_isalpha.c ft_isascii.c ft_isprint.c ft_isdigit.c \
       ft_isalnum.c ft_strlen.c ft_toupper.c ft_tolower.c \
	   ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strlcat.c \
	   ft_strlcpy.c	ft_strnstr.c ft_atoi.c ft_memcmp.c ft_memmove.c \
	   ft_memcpy.c ft_memchr.c ft_memset.c ft_bzero.c ft_strdup.c \
	   ft_calloc.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c 


CFLAGS = -Wall -Werror -Wextra
CC = gcc
OBJS = ${SRCS:.c=.o}
NAME = libft.a
RM = rm -f
LIBC = ar rcs

.c.o: 
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} 

${NAME}:	${OBJS}
		${LIBC} ${NAME} ${OBJS} 

all:	${NAME}

clean:
		${RM} ${OBJS}

fclean:	clean
		${RM}	${NAME}	${OBJS}

re:	fclean	all

.PHONY:	all	re	clean	fclean